# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorPayload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorPayload.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13SensorPayload.proto\"t\n\rSensorPayload\x12\x13\n\x0btemperature\x18\x01 \x02(\r\x12\x0b\n\x03ldr\x18\x02 \x02(\r\x12\x10\n\x08humidity\x18\x03 \x02(\r\x12\x15\n\rsec_since_pir\x18\x04 \x01(\r\x12\x18\n\x10sec_since_fridge\x18\x05 \x01(\r'
)




_SENSORPAYLOAD = _descriptor.Descriptor(
  name='SensorPayload',
  full_name='SensorPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='SensorPayload.temperature', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ldr', full_name='SensorPayload.ldr', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='SensorPayload.humidity', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_since_pir', full_name='SensorPayload.sec_since_pir', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_since_fridge', full_name='SensorPayload.sec_since_fridge', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['SensorPayload'] = _SENSORPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorPayload = _reflection.GeneratedProtocolMessageType('SensorPayload', (_message.Message,), {
  'DESCRIPTOR' : _SENSORPAYLOAD,
  '__module__' : 'SensorPayload_pb2'
  # @@protoc_insertion_point(class_scope:SensorPayload)
  })
_sym_db.RegisterMessage(SensorPayload)


# @@protoc_insertion_point(module_scope)
